language: swift
osx_image: xcode10.2

before_install:
- gem install cocoapods

install: true

stage: Build + Test
env:
- PLATFORM="iOS"
- PLATFORM="macOS"
- PLATFORM="tvOS"
- PLATFORM="watchOS"
script:
- make $PLATFORM
after_success:
- bash <(curl -s https://codecov.io/bash)

jobs:
  include:
  - stage: Pod lib lint
    script:
    - pod lib lint --verbose
  - stage: Deploy Github
    script: skip
    before_deploy:
    - carthage build --no-skip-current --cache-builds
    - carthage archive APNSubGroupOperationQueue
    deploy:
    - provider: releases
      api_key: $GITHUB_OAUTH_TOKEN
      file: APNSubGroupOperationQueue.framework.zip
      skip_cleanup: true
      overwrite: true
      on:
        repo: p4checo/APNSubGroupOperationQueue
        branch: master
        tags: true
  - stage: Deploy Cocoapods
    script: skip
    deploy:
    - provider: script
      script: pod trunk push --allow-warnings
      skip_cleanup: true
      on:
        repo: p4checo/APNSubGroupOperationQueue
        branch: master
        tags: true
